# Generated by Django 3.2.3 on 2021-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('position_z', models.IntegerField()),
                ('magnetic_x', models.IntegerField()),
                ('magnetic_y', models.IntegerField()),
                ('magnetic_z', models.IntegerField()),
                ('rotation_x', models.IntegerField()),
                ('rotation_y', models.IntegerField()),
                ('rotation_z', models.IntegerField()),
                ('acc_x', models.IntegerField()),
                ('acc_y', models.IntegerField()),
                ('acc_z', models.IntegerField()),
                ('tracking_lost', models.BooleanField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
