# Generated by Django 3.2.3 on 2021-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization_x', models.IntegerField()),
                ('localization_y', models.IntegerField()),
            ],
        ),
    ]
