# Generated by Django 3.2.3 on 2021-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransfer', '0002_localization'),
    ]

    operations = [
        migrations.AddField(
            model_name='localization',
            name='time',
            field=models.DateTimeField(default='2021-05-20T00:33:00Z'),
            preserve_default=False,
        ),
    ]
